Add slack notifications

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,3 +1,24 @@
+notify-slack-failure: &notify-slack-failure
+  run:
+    name: Send a slack notification on failure
+    command: |
+      if [ "$NIGHTLY_BUILD" == "true" ]; then
+        export MESSAGE="Build failed for *<$CIRCLE_BUILD_URL|$CIRCLE_JOB>* nightly build."
+        curl -g -H "Content-Type: application/json" -X POST \
+        -d "{\"text\": \"$MESSAGE\", \"attachments\": [{\"color\": \"danger\",\"title\": \"$CIRCLE_JOB nightly build results\",\"title_link\": \"$CIRCLE_BUILD_URL\"}]}" $SLACK_WEBHOOK
+      fi
+    when: on_fail
+notify-slack-success: &notify-slack-success
+  run:
+    name: Send a slack notification on success
+    command: |
+      if [ "$NIGHTLY_BUILD" == "true" ]; then
+        export MESSAGE="Build succeeded for *<$CIRCLE_BUILD_URL|$CIRCLE_JOB>* nightly build."
+        curl -g -H "Content-Type: application/json" -X POST \
+        -d "{\"text\": \"$MESSAGE\", \"attachments\": [{\"color\": \"good\",\"title\": \"$CIRCLE_JOB nightly build results\",\"title_link\": \"$CIRCLE_BUILD_URL\"}]}" $SLACK_WEBHOOK
+      fi
+    when: on_success
+
 build-steps: &build-steps
   steps:
     - checkout
@@ -35,9 +56,17 @@ build-steps: &build-steps
          if [ "$ELECTRON_RELEASE" == "1" ]; then
            echo 'Building Electron for release'
            script/build.py -c R
+           if [ "$?" != "0" ]; then
+             echo 'export BUILD_FAILED=1' >> $BASH_ENV
+             source $BASH_ENV
+           fi
          else
            echo 'Building Electron for debug'
            script/build.py -c D
+           if [ "$?" != "0" ]; then
+             echo 'export BUILD_FAILED=1' >> $BASH_ENV
+             source $BASH_ENV
+           fi
          fi
     - run:
         name: Create distribution
@@ -109,6 +138,8 @@ build-steps: &build-steps
           if [ "$CREATE_TYPESCRIPT_DEFS" == "true" ]; then
             npm run create-typescript-definitions
           fi
+    - <<: *notify-slack-failure
+    - <<: *notify-slack-success
     - persist_to_workspace:
         root: out
         paths:
@@ -165,6 +196,7 @@ jobs:
     environment:
       TARGET_ARCH: arm
       RUN_RELEASE_BUILD: true
+      NIGHTLY_BUILD: true
     <<: *build-defaults
     resource_class: 2xlarge
 
@@ -203,6 +235,7 @@ jobs:
     environment:
       TARGET_ARCH: arm64
       RUN_RELEASE_BUILD: true
+      NIGHTLY_BUILD: true
     <<: *build-defaults
     resource_class: 2xlarge
 
@@ -219,6 +252,7 @@ jobs:
     environment:
       TARGET_ARCH: ia32
       RUN_RELEASE_BUILD: true
+      NIGHTLY_BUILD: true
     <<: *build-defaults
     resource_class: xlarge
 
@@ -242,6 +276,7 @@ jobs:
     environment:
       TARGET_ARCH: x64
       RUN_RELEASE_BUILD: true
+      NIGHTLY_BUILD: true
     <<: *build-defaults
     resource_class: xlarge
 
@@ -259,6 +294,7 @@ jobs:
       TARGET_ARCH: x64
       RUN_RELEASE_BUILD: true
       INSTALL_MACOS_NODE: true
+      NIGHTLY_BUILD: true
     macos:
       xcode: "8.3.3"
     <<: *build-steps
@@ -279,11 +315,14 @@ jobs:
       MAS_BUILD: 1
       RUN_RELEASE_BUILD: true
       INSTALL_MACOS_NODE: true
+      NIGHTLY_BUILD: true
     macos:
       xcode: "8.3.3"
     <<: *build-steps
 
   electron-linux-gn:
+    environment:
+      NIGHTLY_BUILD: true
     docker:
       - image: electronbuilds/electron:0.0.8
     resource_class: 2xlarge
@@ -333,6 +372,8 @@ jobs:
           command: |
              (cd electron/spec && npm i --nodedir=../../third_party/electron_node)
              ./out/Default/electron electron/spec --ci
+      - <<: *notify-slack-failure
+      - <<: *notify-slack-success
 
 workflows:
   version: 2
